### ISSUE TITLE
DIRECT X CANNOT OPEN SOURCE FILE

### ISSUE THREAD

**Issue by GameChampCrafted** [spirthack/CSGOSimple#100]
I get these errors when building

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "d3dx9.h"	CSGOSimple	C:\Users\Administrator\Documents\LothosWare\CSGOSimple-master (1)\CSGOSimple-master\CSGOSimple\render.hpp	6	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory	CSGOSimple	C:\Users\Administrator\Documents\LothosWare\CSGOSimple-master (1)\CSGOSimple-master\CSGOSimple\render.hpp	6

**Comment by anarh1st47** [comment]
Install directx9 sdk

**Comment by Sl4vP0weR** [comment]
https://github.com/spirthack/CSGOSimple/issues/101#issuecomment-604802802
