### ISSUE TITLE
Errors in d3d9.h file (day 2 of this shit)

### ISSUE THREAD

**Issue by cardypastee** [spirthack/CSGOSimple#101]
Errors codes :
E0020
E0029

i am having this issue 2 days.

**Comment by Sl4vP0weR** [comment]
Download the DirectX SDK June 2010
And add path in system variables
![image](https://user-images.githubusercontent.com/42337892/77720175-144cd500-7022-11ea-9919-cadc981407fa.png)
After that u need to add this paths into ur project
![image](https://user-images.githubusercontent.com/42337892/77720304-81f90100-7022-11ea-8807-a2a662f3ee46.png)
