### ISSUE TITLE
help adding features

### ISSUE THREAD

**Issue by VacCatGT** [spirthack/CSGOSimple#102]
so this is an actual issue. when i add a feature i want. i put all the stuff into options.hpp, antiaim.hpp. it builds fine. but i cannot turn the feature on. why is this? if you need more info ask me

**Comment by grimzwaree** [comment]
maybe put it in the menu mongoloid?

**Comment by VacCatGT** [comment]
?

**Comment by Sl4vP0weR** [comment]
@VacCatGT 
Probably, u need to create this:
![image](https://user-images.githubusercontent.com/42337892/77648218-bcbb5480-6fa2-11ea-9c6c-eba8a2581186.png)
![image](https://user-images.githubusercontent.com/42337892/77648428-191e7400-6fa3-11ea-9f30-9838b5569e7c.png)
That's all, if u want - add me in a Discord, mb we can cooperate: Sl4vP0weR#4178
