### ISSUE TITLE
C_BaseCombatWeapon::GetSpread() always returns 0.0

### ISSUE THREAD

**Issue by bbbbbzzzz** [spirthack/CSGOSimple#11]
^

**Comment by anarh1st47** [comment]
whoooops, sorry, fixed by https://github.com/anarh1st47/CSGOSimple/commit/178bdf2322f7c9988b9115c6ec08781a38d153ad

**Comment by bbbbbzzzz** [comment]
Still returns 0.0 :\

**Comment by anarh1st47** [comment]
I cannot check it right now, reopening

**Comment by anarh1st47** [comment]
437 looks legit. 436 returns zeros for me, too. Im sure that getspread actually is 437 vfunc

**Comment by bbbbbzzzz** [comment]
@anarh1st47 but GetInaccuracy have 437 index too

**Comment by bbbbbzzzz** [comment]
im using 437 index for get spread, but still receiving 0.0, wtf

**Comment by bbbbbzzzz** [comment]
i think currently GetInaccuracy is actual GetSpread, because if i turn weapon_recoil_scale to 0, i still receive same values, so GetInaccuracy is wrong

**Comment by anarh1st47** [comment]
try now too

**Comment by anarh1st47** [comment]
issue answer timed out
