### ISSUE TITLE
GetStudioModel(Model()) is returning nullptr

### ISSUE THREAD

**Issue by Lunatrius1** [spirthack/CSGOSimple#112]
Im trying to do simple hitscan (with one hitbox)

`Vector Aimbot::Hitscan(C_BasePlayer* pEnt)
{

	if (g_Autowall.GetDamage(pEnt->GetHitboxPos(HITBOX_CHEST)))
		return pEnt->GetHitboxPos(HITBOX_CHEST);

	return Vector(0.f, 0.f, 0.f);
}`

And I constantly get an error in GetHitboxPos(int hitbox)
`auto studio_model = g_MdlInfo->GetStudiomodel(GetModel());`

**Comment by turtsis** [comment]
Im getting this same error, how did you fix it?
