### ISSUE TITLE
Config crashing game

### ISSUE THREAD

**Issue by elgato69** [spirthack/CSGOSimple#117]
I'm using csgosimple to develop my hack but i cant seem to get the config system to work
every time i click save it crashes with some error in the file xstring 

https://imgur.com/a/0mDE04L

any ideas?

**Comment by effex1337** [comment]
show the full debug info (call stack)

**Comment by elgato69** [comment]
Here you go https://imgur.com/a/e70CE1w

The fout works cause the config file gets created in my game folder so my guess is it's the bytestostring function, i have no idea though

**Comment by elgato69** [comment]
Solved the problem, i had a uint32_t in my options which was causing the exception. Replaced with regular int and problem went away
