### ISSUE TITLE
valve skins and usp-s

### ISSUE THREAD

**Issue by witstof** [spirthack/CSGOSimple#119]
Weapons with valve skins and usp-s arent detecting (IsGun()/IsPistol()/IsRifle() and etc)

**Comment by InfernoLum** [comment]
Provide some code please

**Comment by atheleon** [comment]
> Weapons with valve skins and usp-s arent detecting (IsGun()/IsPistol()/IsRifle() and etc)

Having the same issue, checked for the most recent weapons and such. No such luck fixing it.
