### ISSUE TITLE
Keeps crashing after injection

### ISSUE THREAD

**Issue by KittyLe** [spirthack/CSGOSimple#120]
Hi there, I'm using Visual Studio 2017 (tried 2019 too) and Windows 10. Tried multiple injectors - nothing helps.

After attaching debugger I get this error:
```cpp
An exception was thrown at address 0x00000000 in csgo.exe: 0xC0000005: access violation during execution at address 0x00000000.
```
The line where error happens is this one (15th line in sdk.cpp):
![image](https://user-images.githubusercontent.com/41251521/86052461-b33cff00-ba5f-11ea-9334-b0bed5cd23db.png)

**Comment by martinjanas** [comment]
ctrl + f for "find and replace" - find "client_panorama.dll" and replace it with "client.dll"

**Comment by anarh1st47** [comment]
fixed
