### ISSUE TITLE
Combine new files with old

### ISSUE THREAD

**Issue by Benjjiyy** [spirthack/CSGOSimple#122]
A the title says

**Comment by Benjjiyy** [comment]
i mean, ive used an old ver i found on void or smth of this and made soem cahnges and added tons of features, and scince the new CSGO update it crashes upton inject :( so i belive its because the code is old or the offsets or smth. Which makes me belive i gotta take some updated files and put into the source without getting errors :/

**Comment by ZippoKs** [comment]
If it worked before the trusted update, then update g_GlobalVars

**Comment by Benjjiyy** [comment]
> If it worked before the trusted update, then update g_GlobalVars

how do i update them / where do i find them

**Comment by Benjjiyy** [comment]
> > If it worked before the trusted update, then update g_GlobalVars
> 
> how do i update them / where do i find them

oh wait i found it, i love you so fuckign much thank u (no homo tho)
