### ISSUE TITLE
Getting VAC from this base

### ISSUE THREAD

**Issue by ZippoKs** [spirthack/CSGOSimple#128]
Hello, I've been making a cheat from this base, for about 4 months now (nothing public, only me using it), added rage, legit, more visual stuff, a lot misc stuff (added a lot), but keep on getting VACced, not sure what I should do to prevent it, manual mapping injector (so certain that it's not the case, tried different ones as well).
I'm kind of a new coder, so not sure what to do to prevent it, maybe try other hooknig method, but heard that vmt is still ud.

I get VACced about 12 days after first injection if not gamebanned until then, if banned by ovw, VAC is about 2 days late after OVW ban.

Thanks in advance.

**Comment by AMATEURZ1337** [comment]
You should change ur hooking method to MinHook or something other

**Comment by ZippoKs** [comment]
Tried MinHook, same result.

**Comment by noxppw** [comment]
It's probably your injector. Be sure to be using a undetected injector. Also, check if your aren't doing something that triggers vac. There are some functions and hooks that are detected by itself (even tho _i think_ they should get you a untrusted ban, it's good to check).

**Comment by ZippoKs** [comment]
I tried a lot of injectors, tried GH injector with manual mapping method, tried process hacker, now I have SimpleLoader with changes, but still getting VAC,  but if people aren't getting VAC from csgosimple's base, why am I ? Only funcs I have hooked is ListLeavesInBox, and SceneEnd (+ the ones in csgosimples base), which I don't think they're detected.

**Comment by ghost** [comment]
hey bro wanna share your code?

**Comment by ZippoKs** [comment]
What code? You mean my whole shit? I'd rather not lol

**Comment by ghost** [comment]
@ZippoKs seems like hes just tryna get your code so he can be lazy

**Comment by ghost** [comment]
@iLostMyXbox21 yes, i'm lazy :3

**Comment by Benjjiyy** [comment]
try randoinjector

**Comment by bacontsu** [comment]
just use vac bypasser by osiris developer. or add more junk codes in your source (I dunno if junk codes actually works tho)

**Comment by Benjjiyy** [comment]
> just use vac bypasser by osiris developer. or add more junk codes in your source (I dunno if junk codes actually works tho)

this is a dead thread. please do not bump this anymore

**Comment by bacontsu** [comment]
> > just use vac bypasser by osiris developer. or add more junk codes in your source (I dunno if junk codes actually works tho)
> 
> this is a dead thread. please do not bump this anymore

oof didn't see the dates, sorry about that
