### ISSUE TITLE
Bomb esp not working

### ISSUE THREAD

**Issue by j00r1337** [spirthack/CSGOSimple#132]
bomb esp is not working after newest update, fix plz

**Comment by ghost** [comment]
its open source, why dont you fix it?

**Comment by ZippoKs** [comment]
Update your ClassId enum

**Comment by ZippoKs** [comment]
csgosimple/valve_sdk/misc/Enums.hpp

[Enums.hpp](https://anonfiles.com/L1x8QcGdp4/Enums_hpp)

**Comment by j00r1337** [comment]
> csgosimple/valve_sdk/misc/Enums.hpp
> 
> [Enums.hpp](https://anonfiles.com/L1x8QcGdp4/Enums_hpp)

Thanks for help but for me its still not working...
maybe its cause im using minhook?
https://imgur.com/a/JM2jqHy
` 
case ClassId_CPlantedC4:
 color = Color(255, 255, 9);
 glowObject.m_nGlowStyle = 0;
 break;`

**Comment by ZippoKs** [comment]
As I stated above, you probably didn't get it, download the Enums I uploaded and paste it into valve_sdk/misc/
Or simply in that file set ClassId_CPlantedC4 = 129 (altough I don't recommend this), because other stuff like SmokeGrenadeProjectile will not work also, because of the offsets.
To your comment, no it cannot be because of minhook, I use minhook as well.

**Comment by ZippoKs** [comment]
Or simply in that file set ClassId_CPlantedC4 = 129 (altough I don't recommend this), because other stuff like SmokeGrenadeProjectile will not work also, because of the offsets.

**Comment by ZippoKs** [comment]
Add me on ds: ZippoKs#4639

**Comment by j00r1337** [comment]
> As I stated above, you probably didn't get it, download the Enums I uploaded and paste it into valve_sdk/misc/
> Or simply in that file set ClassId_CPlantedC4 = 129 (altough I don't recommend this), because other stuff like SmokeGrenadeProjectile will not work also, because of the offsets.
> To your comment, no it cannot be because of minhook, I use minhook as well.


Well i actually paste the latest Enums into my source but for some reason its still not working and i have no idea why.
Edit: okay i set  ClassId_CPlantedC4 to 129, and now its working thanks!!
