### ISSUE TITLE
Random Crash by menu

### ISSUE THREAD

**Issue by bbbbbzzzz** [spirthack/CSGOSimple#14]
http://prntscr.com/ks1icx that shows debugger
im using present render instead endscene

**Comment by anarh1st47** [comment]
make sure that g_pDefaultFont is valid.

Show call stack

**Comment by bbbbbzzzz** [comment]
nope, not instantly, idk its full random, i getting only asm in debugger

**Comment by anarh1st47** [comment]
not enough info provided + u r using another renderer + no call stack, i dont see method how can i help u

**Comment by bbbbbzzzz** [comment]
idk what is that, its looks like #13 issue, im just replaced font to impact and rendering in endscene

**Comment by bbbbbzzzz** [comment]
maybe i have that problem because intel graphics?

**Comment by anarh1st47** [comment]
CSGOSimple doesnt use some specific for amd/nvidia code. probably thats imgui bug, i haven't idea

**Comment by anarh1st47** [comment]
try now maybe

**Comment by anarh1st47** [comment]
issue answer timed out
