### ISSUE TITLE
this draws armor bar when armor equals zero.

### ISSUE THREAD

**Issue by gamesense-coder** [spirthack/CSGOSimple#140]
https://github.com/spirthack/CSGOSimple/blob/df4bb4ef20aef408b54b8eb2f99fb1637a5d97e8/CSGOSimple/features/visuals.cpp#L145-L161

this draw armor bar when armor equals 0

UPD: i mean this draw small piece of bar

`if   (armour == 0) return;`

**Comment by linux-fryer** [comment]
Not to sound like a complete asshole but I have no idea what is going on inside of this. I think one of your main issues is the height variable as I have no clue what it's doing. Doing BoxHeight * Your current armor is completely arbitrary and then dividing it by 100 is just why.  Replace it instead with something like this:

```cpp
int ArmorSize = (Box.bottom - Box.top) * (-(Armor / MaxArmor) + 1);
DrawRect(Box.left - 4, Box.top + ArmorSize, Box.left - 3, Box.bottom, ArmorColor, 1.f, true);
```

Hope this helps!
