### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Ketager** [spirthack/CSGOSimple#148]
crash in inject

**Comment by Scui1** [comment]
https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fphotos%2Fimages%2Fnewsfeed%2F001%2F615%2F576%2F509.jpg

**Comment by Scui1** [comment]
![Cool](https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fphotos%2Fimages%2Fnewsfeed%2F001%2F615%2F576%2F509.jpg)

Attach debugger and at least tell where it crashes?

**Comment by IDESOFTWARE2018** [comment]
Hook on Move: //verified->m_cmd = *cmd;
		//verified->m_crc = cmd->GetChecksum(); when you go in game

**Comment by REDLINE-SOFTWARE-2022** [comment]
So the bhop is not working... Index is correct, anyway problem in sequence_number!

oCreateMove(g_CHLClient, 0, sequence_number, input_sample_frametime, active);**

**Comment by nvx0** [comment]
u fixed? mines crashing.

**Comment by REDLINE-SOFTWARE-2022** [comment]
No... We are working on it... 
U can comment this shit and this will stop crashing)

**Comment by Ketager** [comment]
> 
thanks
