### ISSUE TITLE
you forgot some things

### ISSUE THREAD

**Issue by zShikdz** [spirthack/CSGOSimple#19]
here is the fixed functions: 

`bool C_BaseEntity::IsPlayer()
{
	return GetClientClass()->m_ClassID == ClassId_CCSPlayer;
}`

`bool C_BaseEntity::IsWeapon()
{
	int iClassId = GetClientClass()->m_ClassID;

	return iClassId == ClassId_CAK47 
		|| iClassId == ClassId_CSCAR17 
		|| iClassId == ClassId_CDEagle 
		|| iClassId == ClassId_CFlashbang 
		|| iClassId == ClassId_CHEGrenade
		|| iClassId == ClassId_CSmokeGrenade
		|| iClassId == ClassId_CMolotovGrenade
		|| iClassId == ClassId_CDecoyGrenade
		|| iClassId == ClassId_CIncendiaryGrenade
		|| (iClassId >= ClassId_CWeaponAug && iClassId <= ClassId_CWeaponXM1014);
}`

It broke for my atleast.

What i found was wrong while using this base to my cheat, sorry if theres something still left!

**Comment by anarh1st47** [comment]
Thanks for your contribution, I'll merge it asap
Feel free reporting another bugs and fixes :)

**Comment by zShikdz** [comment]
no problem, Love this source and still using it since I started making internals!

**Comment by anarh1st47** [comment]
Should be fixed, try it now(updated vfunc indexes, not checking client class)

**Comment by hsurk** [comment]
> Should be fixed, try it now(updated vfunc indexes, not checking client class)

I haven't checked if it needs changing but the commit is called IsWeapon... and IsWeapon() didn't change.

**Comment by anarh1st47** [comment]
hmm i should be changed it from 160 to 160 :trollface:

**Comment by anarh1st47** [comment]
after merging your merge requests it can be closed?

**Comment by anarh1st47** [comment]
issue answer timed out
