### ISSUE TITLE
C_BasePlayer::GetFlashBangTime() always returns 0.0000

### ISSUE THREAD

**Issue by suaducrus** [spirthack/CSGOSimple#28]
GetFlashBangTime() seems to always returns 0.0000 for me, anyone else have this issue? is the pattern outdated by anychance?

**Comment by anarh1st47** [comment]
hm, probably its outdated, im not using it in my cheat now, IsFlashed broken, too? Im using m_flFlashMaxAlpha now, i'll add this version of IsFlashed asap

**Comment by anarh1st47** [comment]
![image](https://user-images.githubusercontent.com/16495272/50513817-1f295a80-0aab-11e9-8e38-0890075e1f91.png)
with new isflashed should works https://github.com/spirthack/CSGOSimple/commits/master

**Comment by suaducrus** [comment]
Yep, IsFlashed() does work, no problem there. 
I was trying to get the time flash ends so i can compare with curtime and disable my flash check 1 sec before the flash actually ends.

**Comment by suaducrus** [comment]
Probably remove or comment out GetFlashBangTime() for now?

**Comment by anarh1st47** [comment]
Ye i was thinked about removing it, but im not sure that it doesntworks, gonna test it later. If it doesnt works i will remove, and if it works i will close it without any changes, cuz its a base and unused staff may be used at own projs

**Comment by anarh1st47** [comment]
removed. thanks
