### ISSUE TITLE
fnAccept() not working?

### ISSUE THREAD

**Issue by suaducrus** [spirthack/CSGOSimple#30]
fnAccept("") is being called, but doesn't seem to auto accepting?
I couldn't find any info on the pattern being outdated, perhaps I broke something?

**Comment by ValveDev377** [comment]
🤔

**Comment by anarh1st47** [comment]
I cannot test it few days, we r using same pattern but accepting match not in the same tick when it found

**Comment by suaducrus** [comment]
Seems to be working again... 🤔🤔
