### ISSUE TITLE
RenderText() seems to only use Droid Sans even when another font is set

### ISSUE THREAD

**Issue by suaducrus** [spirthack/CSGOSimple#31]
I've been trying to figure out how to RenderText without the outline, which lead me to trying another font and see if it's part of the font.

I've defined and created a new font in GetFonts(),
Passing it to RenderText() however, dosn't seem to affect the font of the text🤔

Sry this might just be cuz I lack understanding of ImGui,
does ImGui::PushFont() have to be called on top of the PushTextureId() that is already in RenderText()?

**Comment by anarh1st47** [comment]
How r u using this?
```
g_pIconFont = imfnts->AddFontFromMemoryCompressedTTF(Icons_compressed_data, Icons_compressed_size, 18.f);
Render::Get().RenderText(text, x, y, fontsz, clr, false, font);
```
should works

**Comment by ultramemer** [comment]
about the outline, if you dont want it then you need to remove this
https://github.com/spirthack/CSGOSimple/blob/master/CSGOSimple/render.cpp#L109-L112
https://github.com/spirthack/CSGOSimple/blob/master/CSGOSimple/render.cpp#L118-L121

**Comment by suaducrus** [comment]
> Edit NVM i'm stupid the issue is make sure you pass the boolean centered before the font i forgot that and was causing issues.

The font is not being changed for me even when i have passed the center boolean

RenderText(const std::string& text, const ImVec2& position, float size, Color color, bool center = false, ImFont* pFont = g_pDefaultFont);

**Comment by Vladislavik36** [comment]
https://github.com/spirthack/CSGOSimple/commit/55e6e39b27df306130c911736abec1f2857b0569
i've added second font for example and it works.
