### ISSUE TITLE
ESP not working

### ISSUE THREAD

**Issue by surblazer** [spirthack/CSGOSimple#4]

**Comment by anarh1st47** [comment]
Good morning, 
ESP works perfectly for me:
https://imgur.com/a/lF6LK17
Please provide more info about ur Issue.

**Comment by surblazer** [comment]
Maybe it's only my Intel HD issue. But render ESP without imgui by FrameStageNotify is working perfect.

**Comment by anarh1st47** [comment]
Objects pushed to render list? Does Menu rendering? Did u update smth urself?

**Comment by surblazer** [comment]
I recompile your source again but it didnt working. Menu is rendering. I think problem in my integrated Intel HD Graphics.

**Comment by anarh1st47** [comment]
I've tested csgosimple on intel hd 630, works fine: https://imgur.com/a/ztSsMou
Have u another ideas?
@surblazer

**Comment by surblazer** [comment]
I think, You can close this thread, because I have very old Intel HD 2000 :)

**Comment by anarh1st47** [comment]
I dont want close unsolved issue

**Comment by surblazer** [comment]
Hello! I download and recompile ur source, and I see that visuals and watermark don't work again, chams works. If I can tell u useful information, tell me what.

**Comment by anarh1st47** [comment]
hello, 
could you set breakpoint here and show the draw_list_act value? https://github.com/anarh1st47/CSGOSimple/blob/master/CSGOSimple/render.cpp#L80

Same with https://github.com/anarh1st47/CSGOSimple/blob/master/CSGOSimple/render.cpp#L73 and draw_list

**Comment by anarh1st47** [comment]
issue answer timed out
