### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by jurelann123** [spirthack/CSGOSimple#40]
Sorry noob question but is there a tutorial on how to use this or atleast a guide.. Total newbie here :)

**Comment by anarh1st47** [comment]
To build project you can download zip, open it in visual studio(i use 2017 community), install directx9 sdk, select x86 debug/release in visual studio project and press build button. than open csgo and start start injector.exe. 

This is a base which aimed at developers and im not sure about detection status, anynway it might be sigged. I would recommend you use it on new free steam account also
