### ISSUE TITLE
i got vac ban.

### ISSUE THREAD

**Issue by xor-128** [spirthack/CSGOSimple#44]
i added aimbot, silent aim, edge jump, grenade prediction, backtrack, disable postprocess, night mode.

i removed glowobjectmanager.

it's not untrusted, it's vac ban. and i got vac ban after 3 days.

my doubts
1- Detected hooking method. (probably not)
2- My injection method is loadlibrary (probably not too)
3- I injecting debug build (b1g doubt)
4- my post process disabler and night mode like this
`static auto mat_force_tonemap_scale = g_CVar->FindVar("mat_force_tonemap_scale");

mat_force_tonemap_scale->RemoveFlags(FCVAR_CHEAT);

g_EngineClient->ExecuteClientCmd(std::string("mat_force_tonemap_scale "+std::to_string(g_Options.night_mode_factor)).c_str());
`

if you see one of them triggering vac, please reply it.

**Comment by anarh1st47** [comment]
Its hard to say why you got banned, probably base detected itself, but im using a lot of code from this base with small changes without bans.

Your doubts:

Hooking: can be detected but last time when i've checked shadow vmt it was undetected, i'm not using this method now so idk

LoadLibrary: I'm using processhacker and own lla injector without bans, so it should be ud

Debug build: VS debug symbols generator detected  :trollface: 
I'm injecting debug(or debug o2) builds every time when i'm playing csgo, didnt triggered vac

NightMode: idk about your method, im using ColorModulate on materials to achieve it, no bans.


I see only two detection vectors here: vmt hooker or probably base sigged itself. Try another hooker, for example, MinHook(its patching functions but ud by vac), if no vac - vmt detected

**Comment by JimmyBassy** [comment]
Happens the same to me when I implement the nightmode, I think that Valve is now checking for"sv_skyname" cvar. I only get VAC'd when I activate the nightmode. Maybe somebody can check if this is true.

**Comment by anarh1st47** [comment]
I've played with only this base(while test some commits) few time and didnt get ban

**Comment by Shaxzy** [comment]
I didn’t get VAC using this either.

**Comment by 0xE232FE** [comment]
Did you inject ManualMap?

**Comment by Sl4vP0weR** [comment]
U can got VAC only by Overwatch I think

**Comment by ZeroXKiritsu** [comment]
This VMT It's not detected, it's the stout itself, most likely it's because of the debag or the load library inject, I used the backbone mmap and all right.

**Comment by ghost** [comment]
> 
> 
> U can got VAC only by Overwatch I think

what?

**Comment by es3n1n1337** [comment]
Omg

**Comment by xor-128** [comment]
why you guys resurrected this issue. I never played CS:GO in 2 years...
