### ISSUE TITLE
Unable to use after updating yesterday, please update

### ISSUE THREAD

**Issue by carrywu** [spirthack/CSGOSimple#46]
@

**Comment by anarh1st47** [comment]
![image](https://user-images.githubusercontent.com/16495272/56780158-e1cda300-67e6-11e9-8052-d626bbbd7dcd.png)
Please specify whats wrong, working fine for me

**Comment by JimmyBassy** [comment]
If it's because of the menu you have to comment out the line that sets the size of the window, at least that was the issue I was having

**Comment by anarh1st47** [comment]
do u still have some issues?
