### ISSUE TITLE
crashing on get_interface

### ISSUE THREAD

**Issue by iBlooze** [spirthack/CSGOSimple#48]
downloaded source, compiled source
![image](https://user-images.githubusercontent.com/23624009/56875504-161faa00-6a07-11e9-9803-d157f4a12ef1.png)
havent changed a single thing in the source

**Comment by iBlooze** [comment]
build tools v142
visual studio 2019
Windows 10

**Comment by anarh1st47** [comment]
![image](https://user-images.githubusercontent.com/16495272/56909659-4f145900-6ab1-11e9-91c1-e3e76d74afc4.png)
Works fine for me

**Comment by anarh1st47** [comment]
reopen if still exists, but with additional info
