### ISSUE TITLE
crashing when changing knife m_iItemDefinitionIndex.

### ISSUE THREAD

**Issue by denizdeni** [spirthack/CSGOSimple#51]
`
pEntity->m_Item().m_iItemIDHigh() = -1;
				pEntity->m_Item().m_iAccountID() = player_info.xuid_low;
				pEntity->m_Item().m_iEntityQuality() = 3;
				std::string customname(WeaponSettings[std::to_string(pLocal->m_iTeamNum() == 3 ? WEAPON_KNIFE : WEAPON_KNIFE_T)]["Custom Name"].get<std::string>());
				if (customname != "" || customname != "None")
					strncpy(pEntity->m_Item().m_iCustomName(), customname.c_str(), sizeof(char[32]));
				pEntity->m_nFallbackPaintKit() = WeaponSettings[std::to_string(pLocal->m_iTeamNum() == 3 ? WEAPON_KNIFE : WEAPON_KNIFE_T)]["Paint Kit"].get<int>();
				pEntity->m_flFallbackWear() = WeaponSettings[std::to_string(pLocal->m_iTeamNum() == 3 ? WEAPON_KNIFE : WEAPON_KNIFE_T)]["Fallback Wear"].get<float>();
				auto &defindex = pEntity->m_Item().m_iItemDefinitionIndex();
				if (defindex != knife_model_info.at(WeaponSettings[std::to_string(pLocal->m_iTeamNum() == 3 ? WEAPON_KNIFE : WEAPON_KNIFE_T)]["Knife model"]).index) {
					defindex = knife_model_info.at(WeaponSettings[std::to_string(pLocal->m_iTeamNum() == 3 ? WEAPON_KNIFE : WEAPON_KNIFE_T)]["Knife model"]).index;
					auto override_model_index = g_MdlInfo->GetModelIndex(knife_model_info.at(WeaponSettings[std::to_string(pLocal->m_iTeamNum() == 3 ? WEAPON_KNIFE : WEAPON_KNIFE_T)]["Knife model"]).knife);
					pEntity->SetModelIndex(override_model_index);
					pEntity->GetClientNetworkable()->PreDataUpdate(0);

`

it's working few days ago but it's not working anymore. i updated cheat for last update. still not working.

**Comment by AdNine87** [comment]
what the debuger is showing?

**Comment by denizdeni** [comment]
nothing

**Comment by anarh1st47** [comment]
try after update
