### ISSUE TITLE
chams bugged

### ISSUE THREAD

**Issue by fireframeloader** [spirthack/CSGOSimple#52]
chams is bugging and not walling

![csgo_2019-05-02_20-47-44](https://user-images.githubusercontent.com/49798064/57113604-af0e3800-6d1b-11e9-848c-099dcf24b070.png)

**Comment by fireframeloader** [comment]
![imagem](https://user-images.githubusercontent.com/49798064/57113735-4ecbc600-6d1c-11e9-83ec-ca4650b11b42.png)
just this

**Comment by fireframeloader** [comment]
if u want more information tell me

**Comment by fireframeloader** [comment]
if u want more information tell me

**Comment by anarh1st47** [comment]
Its question about your chams method/settings, because chams in this csgosimple doesnt work at all yet :trollface: (#47)
