### ISSUE TITLE
Lag issue?

### ISSUE THREAD

**Issue by xAkiraMiura** [spirthack/CSGOSimple#56]
After the recent update I noticed that sometimes actions don't go through (i.e. buying items, sending chat messages, bhopping, switching weapons). 
I don't think this is due to my fakelag because its config option is off. 

Additionally my fakelag stopped working and causes actual lag.

**Comment by xAkiraMiura** [comment]
Apon further testing I have fixed my problem and it doesn't affect master.

**Comment by y7QrAO0uXt** [comment]
maybe createmove issue
