### ISSUE TITLE
CanFire returning wrong value

### ISSUE THREAD

**Issue by vozizir** [spirthack/CSGOSimple#67]
Hello, there is a problem in  [C_BaseCombatWeapon::CanFire](https://github.com/spirthack/CSGOSimple/blob/26aa1a9fcad20f97802321a896857b38a92749ff/CSGOSimple/valve_sdk/csgostructs.cpp#L60)(already gone reported here and not solved: https://github.com/spirthack/CSGOSimple/issues/8), CanFire returning 1 in situations that shouldn't, for example, if you are already in shooting(which should return 0, since you are already in shoot and increase m_flNextPrimaryAttack), it seems to me that it is a wrong calculation in m_nTickBase, since in any situation servertime is less than m_flNextPrimaryAttack.

**Comment by anarh1st47** [comment]
can u check it right now?

**Comment by anarh1st47** [comment]
#8 looks fixed
