### ISSUE TITLE
Rank revealer

### ISSUE THREAD

**Issue by Kron1Q** [spirthack/CSGOSimple#69]
Delete old one in Utils and add this one into createmove, sry i am too lazy to make a pull request

if (g_Options.misc_rankrevealer && cmd->buttons & IN_SCORE)
 g_CHLClient->DispatchUserMessage(CS_UM_ServerRankRevealAll, 0, 0, nullptr);

**Comment by anarh1st47** [comment]
@P45H3 do refactoring

**Comment by sarbadelin** [comment]
code for faceit or esea have
