### ISSUE TITLE
Esp enabled crashing

### ISSUE THREAD

**Issue by privileged8222** [spirthack/CSGOSimple#70]
when i press enable on esp tab the game crashes.

**Comment by Vladislavik36** [comment]
debug it

**Comment by privileged8222** [comment]
> debug it

cba

**Comment by cuntfucker66** [comment]
in void Visuals::AddToDrawList() change if (i <= 65) to if (i < 65)

**Comment by anarh1st47** [comment]
should be fixed, check?

**Comment by privileged8222** [comment]
Currently on holiday will check in 2 wks

**Comment by anarh1st47** [comment]
feel free reopen if exists
