### ISSUE TITLE
C_BaseCombatWeapon::CanFire() returns wrong value

### ISSUE THREAD

**Issue by bbbbbzzzz** [spirthack/CSGOSimple#8]
if im switching my weapon fast, and checking on CanFire, it says wrong value , im trying to do this:
`	if (!(cmd->buttons & IN_ATTACK) && weapon->CanFire())
			cmd->buttons |= IN_ATTACK;`
^^ simple autofire , but it break when im switching weapons fast (e.g pressed 1 , instantly 2, and again 1), fix pls

**Comment by anarh1st47** [comment]
https://www.youtube.com/watch?v=1mF8JnKIWio&feature=youtu.be
Cannot reproduce, provide more info

**Comment by bbbbbzzzz** [comment]
https://youtu.be/K0LBqwycYw4

**Comment by anarh1st47** [comment]
Yes, successfully reproduced. CanShoot works fine, sending in_attack but doesnt shooting.  
![image](https://user-images.githubusercontent.com/16495272/44700772-b47ff800-aa93-11e8-8e19-e5cfcf58778d.png)

Will search whats wrong, strange

**Comment by anarh1st47** [comment]
I was wrong, issue is that u cannot shoot in first tick after weapon switch, so CanFire should return false, but it return true; fixed. Thanks for bug reporting.

**Comment by bbbbbzzzz** [comment]
still not fixed

**Comment by anarh1st47** [comment]
I've tested it a lot with 
`auto activeweapon = g_LocalPlayer->m_hActiveWeapon();


		if (cmd->buttons ^ IN_ATTACK && activeweapon && activeweapon->IsWeapon() && !activeweapon->IsKnife() && activeweapon->CanFire()) cmd->buttons |= IN_ATTACK;
` and it works perfectly

**Comment by bbbbbzzzz** [comment]
me too, but  still have this bug
https://youtu.be/K0LBqwycYw4

**Comment by bbbbbzzzz** [comment]
https://www.youtube.com/watch?v=2xm3BpSh8dc&feature=youtu.be

**Comment by anarh1st47** [comment]
Lol, idk; going sleep now, will try 2 fix later

**Comment by anarh1st47** [comment]
I got an idea: this code brokens if called more than one time per tick. Should store inactive tick too. Will perform when get pc

Do u call CanFire many times per tick?

**Comment by bbbbbzzzz** [comment]
2 times, try use curtime instead flServerTime, that will not help but will be a bit properly

**Comment by bbbbbzzzz** [comment]
CanFire brokes with G3SG1 idk why, maybe because calling 3-4 times at tick

**Comment by anarh1st47** [comment]
test it now https://github.com/anarh1st47/CSGOSimple/commit/ecef03db1596d20afcc3fc7ce74d7c493eaef2bc

**Comment by bbbbbzzzz** [comment]
semi-fixed, still show wrong value when im swap weapon, but autofire works

**Comment by anarh1st47** [comment]
whats wrong value? CanFire returns true when u'r swapping weapon?

**Comment by bbbbbzzzz** [comment]
yes

**Comment by bbbbbzzzz** [comment]
it also returns false when im trying attack with knife

**Comment by anarh1st47** [comment]
Knife cannot fire

**Comment by bbbbbzzzz** [comment]
but CanFire with G3SG1 or SCAR20 returns false when im shooting more then 1 bullet, with autofire you cannot see that, but if you try make `if (cmd->buttons & IN_ATTACK && weapon->CanFire()) Aimbot(cmd);`  and try to shoot constantly youll see what CanFire returns false, but you still can fire and you do

**Comment by anarh1st47** [comment]
can u check it right now?

**Comment by denizdeni** [comment]
> can u check it right now?

its fixed right now. you can close this issue

**Comment by anarh1st47** [comment]
thanks
