### ISSUE TITLE
green cum effect on skins [fix]

### ISSUE THREAD

**Issue by B0ruK** [spirthack/CSGOSimple#82]
found it by myself accidentaly funny thing there are some p2c's outhere that can't fix this

when creating material

{
  "$basetexture" "vgui/white_additive" <-- delete this and it works as it used 2
  "$ignorez"      "1"
  "$envmap"       ""
  "$nofog"        "1"
  "$model"        "1"
  "$nocull"       "0"
  "$selfillum"    "1"
  "$halflambert"  "1"
  "$znearer"      "0"
  "$flat"         "1"
}

https://imgur.com/a/rtDD7wJ <- before

https://imgur.com/a/3W8qvAj <- after

**Comment by denizdeni** [comment]
i love this effect.

it's reminds me my alien father...

**Comment by anarh1st47** [comment]
thanks, looks like works! will fix in next commit soon. Also looks like its possible just dont create materials, using existsing

**Comment by numero69** [comment]
ghetto f1x

**Comment by denizdeni** [comment]
Creating materials for chams is worst method and you can ban easily. Because if you dont have sv_pure bypass. Server know you created and used custom packages.

**Comment by mytopdog** [comment]
This was on unknowncheats with these exact images so you didn't find this yourself.

**Comment by anarh1st47** [comment]
should be fixed with https://github.com/spirthack/CSGOSimple/commit/245f33ce08cd8455de94dd48bd2ef54f9403c7d3
